### PR TITLE
Introduce layout for the app windows

### PR DESCRIPTION
**Pull request by janus2**
* Introduce layout
* Use BCardLayout for settings
* Fix a crash from update frequency
* Update browser selection
* Remove useless class
* Clean up the code

### CODE REVIEW

**Comment by diversys** [comment]
Cool! Looking forward to checking it out! Maybe you're also interested in https://github.com/HaikuArchives/Beam/issues/1?

**Comment by diversys** [comment]
Hmm, Opening Settings window make the app crash.

**Comment by janus2** [comment]
Have you rebuild the library?

**Comment by diversys** [comment]
No, but I just did make clean and rebuild and it still crashes.

**Comment by janus2** [comment]
make clean in the sources directory?
doesn't rebuild the static libraries

**Comment by diversys** [comment]
No, but I just did make clean and rebuild and it still crashes.

```
	thread 159285: w>BePodder 
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x70f530f0	0x1fdc0f4	BTwoDimensionalLayout::SetInsets(float, float, float, float) + 0x28 
			Disassembly:
				BTwoDimensionalLayout::SetInsets(float, float, float, float):
				0x01fdc0cc:               55  push %ebp
				0x01fdc0cd:             89e5  mov %esp, %ebp
				0x01fdc0cf:           83ec10  sub $0x10, %esp
				0x01fdc0d2:               56  push %esi
				0x01fdc0d3:               53  push %ebx
				0x01fdc0d4:       e800000000  call 0x1fdc0d9
				0x01fdc0d9:               5b  pop %ebx
				0x01fdc0da:     81c33f511600  add $0x16513f, %ebx
				0x01fdc0e0:           8b7508  mov 0x8(%ebp), %esi
				0x01fdc0e3:           d9450c  fld 0xc(%ebp)
				0x01fdc0e6:           83c4f4  add $0xfffffff4, %esp
				0x01fdc0e9:           83ec04  sub $0x4, %esp
				0x01fdc0ec:           d91c24  fstp (%esp)
				0x01fdc0ef:       e88818f7ff  call 0x1f4d97c
				0x01fdc0f4:     d99eb4000000  fstp 0xb4(%esi) <--

			Frame memory:
				[0x70f530c0]  .@{.<....0.p....   00 40 7b c4 3c 1e 2e 01 f8 30 f5 70 d9 c0 fd 01
				[0x70f530d0]  <...\6,..1.p81.p   3c 1e 2e 01 5c 36 2c 01 08 31 f5 70 38 31 f5 70
				[0x70f530e0]  =.(..{..81.pF.(.   3d fa 28 01 08 7b 94 18 38 31 f5 70 46 fa 28 01
		0x70f53140	0x128fa41	SettingsWindow::AddBox(char*, PBox*) + 0x49 
		0x70f53200	0x125d989	__16BPSettingsWindow + 0x9d 
		0x70f532a0	0x1283813	MainWindow::MessageReceived(BMessage*) + 0x1a7 
		0x70f532d0	0x1f08fad	BLooper::DispatchMessage(BMessage*, BHandler*) + 0x59 
		0x70f534b0	0x1ff2d48	BWindow::DispatchMessage(BMessage*, BHandler*) + 0x182c 
		0x70f53510	0x1ff73c2	BWindow::task_looper() + 0x28e 
		0x70f53540	0x1f0a455	BLooper::_task0_(void*) + 0x3d 
		0x70f53568	0x2504951	thread_entry + 0x21 
		00000000	0x611fe250	commpage_thread_exit + 0 
```

**Comment by janus2** [comment]
You must go in BePodder/library/libfunky
make clean
make
return to the BePodder/sources
delete the executable or make clean
make

**Comment by janus2** [comment]
It's a very tricky setting

**Comment by janus2** [comment]
A just cloned the HaikuArchives repository and I compiled the three static libraries and the application and everything works... I think you are linking the app to the old library.

**Comment by janus2** [comment]
Approved?

**Comment by diversys** [comment]
That fixed it, thanks! :)

**Pull request merged**
